_target_: cellpoint.utils.transform.Compose
transforms:
  - _target_: cellpoint.utils.transform.PointcloudFarthestPointSampling
    num_points: 2048
    expand_ratio: 1.0
    max_points: 2048

  - _target_: cellpoint.utils.transform.PointcloudRotate