_target_: cellpoint.utils.transform.Compose
transforms:
  - _target_: cellpoint.utils.transform.PointcloudFarthestPointSampling
    num_points: 8192
    expand_ratio: 1.0
    max_points: 8192

  - _target_: cellpoint.utils.transform.PointcloudScaleAndTranslate
    scale_low: 0.8
    scale_high: 1.2
    translate_range: 0.1