defaults:
  - model/share@share
  - model/extractor@extractor
  - model/classification_head@classification_head
  - model/accuracy@acc_metrics
  - _self_

_target_: cellpoint.model.PQAEFinetune

resume_ckpt_path: null  # for resuming training (loads full training state)
pretrained_ckpt_path: null  # for loading pretrained weights (extractor and/or head)