defaults:
  - system: finetune
  - data: finetune
  - logger: [wandb]
  - callback: finetune
  - trainer: default
  - hydra: default
  - _self_           

# Global settings
project_name: "3DCellPoint"
seed: 42