defaults:
  - system: pretrain_test
  - data: pretrain_test
  - logger: null
  - callback: null
  - trainer: default
  - hydra: default
  - _self_           

# Global settings
project_name: "3DCellPoint"
seed: 42