defaults:
  - system: pretrain
  - data: pretrain_redblood
  - logger: [wandb]
  - callback: pretrain
  - trainer: default
  - hydra: default
  - _self_           

# Global settings
project_name: "3DCellPoint"
seed: 42