splits: ["train", "test"] # used in pretrain, ignored in finetune
num_points: null # do not set here, set fps in training config


# Datasets to be used, when pretrain, many can be selected; when finetune, only one can be selected.
selected:
  - shapenetcorev2

available:
  shapenet55_34:
    _target_: "cellpoint.datasets.ShapeNetDataset"
    pc_path: "/home/verve/Project/research/CellPoint/datasets/shapenet55-34/pcl"
    split_path: "/home/verve/Project/research/CellPoint/datasets/shapenet55-34/splits"
    num_points: ${...num_points}
  modelnet40:
    _target_: "cellpoint.datasets.HDF5Dataset"
    path: "/home/verve/Project/research/CellPoint/datasets/modelnet40"
    num_points: ${...num_points}
  intestine:
    _target_: "cellpoint.datasets.HDF5Dataset"
    path: "/home/verve/Project/research/CellPoint/datasets/intestine"
    num_points: ${...num_points}
  redblood:
    _target_: "cellpoint.datasets.HDF5Dataset"
    path: "/home/verve/Project/research/CellPoint/datasets/redblood/class12"
    num_points: ${...num_points}
  intrA:
    _target_: "cellpoint.datasets.HDF5Dataset"
    path: "/home/verve/Project/research/CellPoint/datasets/intrA"
    num_points: ${...num_points}
  shapenetcorev2:
    _target_: "cellpoint.datasets.HDF5Dataset"
    path: "/home/verve/Project/research/CellPoint/datasets/shapenetcorev2"
    num_points: ${...num_points}

