defaults:
  - dataset: default
  - model: pqae
  - training: pretrain
  - hydra: default
  - wandb: default
  - _self_

# global variables
project_name: "3DCellPoint"
task: "pretrain" # "pretrain" or "finetune"
